/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    ClarificationCard: typeof import('./components/chat/ClarificationCard.vue')['default']
    MarkdownRenderer: typeof import('./components/chat/MarkdownRenderer.vue')['default']
    MessageItem: typeof import('./components/chat/MessageItem.vue')['default']
    RagFlowCard: typeof import('./components/chat/RagFlowCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/common/Sidebar.vue')['default']
    SourceChips: typeof import('./components/chat/SourceChips.vue')['default']
    UploadDropzone: typeof import('./components/documents/UploadDropzone.vue')['default']
  }
}
